platform :ios, '13.0'
use_frameworks!

target 'com.awareframework.ios.sensor.gyroscope_Example' do
  pod 'com.awareframework.ios.sensor.gyroscope', :path => '../'

  target 'com.awareframework.ios.sensor.gyroscope_Tests' do
    inherit! :search_paths

    
  end
end
